export const BASIC_TYPE_SET = new Set([
    "never", "boolean", "string", "number", "bigint", "symbol",
    "void", "Boolean", "String", "Number", "BigInt", "Symbol",
    "boolean[]", "string[]", "number[]", "bigint[]", "symbol[]",
    "Array<boolean>", "Array<string>", "Array<number>", "Array<bigint>", "Array<symbol>",
    "Array<Array<boolean>>", "Array<Array<string>>", "Array<Array<number>>", "Array<Array<bigint>>",
    "Array<Array<symbol>>",
    "Record<string,number>", "Record<string,boolean>", "Record<string,string>", "Record<string,bigint>",
    "Record<string,symbol>", "Record<string,Array<boolean>>", "Record<string,Array<string>>", "Record<string,Array<number>>",
    "Promise<bigint>", "Promise<boolean>", "Promise<string>", "Promise<number>", "Promise<symbol>",
    "Promise<Array<boolean>>", "Promise<Array<string>>", "Promise<Array<number>>",
    "Map<string,boolean>", "Map<string,string>", "Map<string,number>", "Map<string,bigint>",
    "Map<number,string>", "Map<number,number>", "Map<boolean,string>", "Map<boolean,number>", "Map<boolean,boolean>",
    "Set<boolean>", "Set<string>", "Set<number>", "Set<bigint>", "Set<symbol>",
    "string | number", "number | boolean", "string | bigint", "string | null",
    "string | boolean", "string | symbol", "number | boolean", "number | symbol", "boolean | symbol",
    "string | number | boolean", "string | number | bigint", "string | boolean | bigint",
    "number | boolean | bigint", "string | number | symbol", "string | boolean | symbol",
    "number | boolean | symbol", "string | number", "string | boolean",
    "() => void", "() => string", "() => number", "() => boolean",
    "(string) => void", "(string) => string", "(string) => number", "(string) => boolean",
    "(number) => void", "(number) => string", "(number) => number", "(number) => boolean",
    "(boolean) => void", "(boolean) => string", "(boolean) => number", "(boolean) => boolean",
    "(string, number) => boolean", "(string, boolean) => number", "(number, boolean) => string",
    "(string, number, boolean) => string",
    "(string | number) => boolean", "(string | boolean) => number", "(number | boolean) => string",
    "(string | number | boolean) => string",
    "() => Promise<string>", "() => Promise<number>", "() => Promise<boolean>",
    "(string) => Promise<number>", "(number) => Promise<string>", "(boolean) => Promise<number>",
    "(string, number) => Promise<boolean>", "(string, boolean) => Promise<number>",
    "() => Array<string>", "() => Array<number>", "() => Array<boolean>",
    "(string) => Array<number>", "(number) => Array<string>", "(boolean) => Array<number>",
    "() => Map<string,string>", "() => Map<string,number>", "() => Map<number,string>",
    "(string) => Map<string,number>", "(number) => Map<string,string>",
    "() => Set<string>", "() => Set<number>", "() => Set<boolean>",
    "(string) => Set<number>", "(number) => Set<string>", "(boolean) => Set<number>",
    "{a: string, b: number}", "{a: string, b: number, c: boolean}",
    "{a: string, b: number, c: boolean}", "{a: string, b: number, c: boolean, d: symbol}",
    "{a: string, b: number, c: boolean[], d: symbol}", "{a: string, b: Set<number>, c: boolean, d: symbol}",
    "{a: string[], b: number, c: boolean[], d: symbol, f: bigint}",
    "{a: string, b: number, c: boolean, d: symbol, f: bigint}",
    "{a: string, b: Array<number>, c: boolean, d: symbol, f: bigint, g: (string) => number}",
    "{a: string, b: Map<string,number>, c: boolean, d: symbol, f: bigint, g: (string) => number, h: (number) => string}",
    "{a: string, b: Set<number>, c: boolean, d: symbol, f: bigint, g: (string) => number, h: (number) => string, i: (boolean) => number}",
    "[string, number, boolean, symbol, bigint]", "[string, number, boolean]",
    "[string, number]", "[number, boolean]", "[string, boolean]", "[boolean, string]",
    "[string, number, boolean]", "[number, string, boolean]", "[boolean, string, number]",
    "[string, number, boolean, symbol]", "[number, string, boolean, symbol]",
    "[string, number, boolean, symbol, bigint]", "[number, string, boolean, symbol, bigint]",
    "[string, number, boolean, symbol, bigint]", "[number, string, boolean, symbol, bigint, Promise<string>]",
    "[string, number, boolean, symbol, bigint, Promise<string>]", "[number, string, boolean, symbol, bigint, Promise<string>]"
]);
